<?php
declare(strict_types=1);

namespace Panth\Blog\Console\Command;

use Magento\Framework\App\ResourceConnection;
use Magento\Framework\App\State;
use Magento\Store\Model\StoreManagerInterface;
use Symfony\Component\Console\Command\Command;
use Symfony\Component\Console\Input\InputInterface;
use Symfony\Component\Console\Output\OutputInterface;

class UrlRewriteRebuildCommand extends Command
{
    private const ENTITY_TYPES = [
        'panth_blog_post'     => ['table' => 'panth_blog_post',     'id' => 'post_id',     'urlKey' => 'url_key', 'route' => 'blog/post/view',     'prefix' => ''],
        'panth_blog_category' => ['table' => 'panth_blog_category', 'id' => 'category_id', 'urlKey' => 'url_key', 'route' => 'blog/category/view', 'prefix' => 'category/'],
        'panth_blog_tag'      => ['table' => 'panth_blog_tag',      'id' => 'tag_id',      'urlKey' => 'url_key', 'route' => 'blog/tag/view',      'prefix' => 'tag/'],
        'panth_blog_author'   => ['table' => 'panth_blog_author',   'id' => 'author_id',   'urlKey' => 'url_key', 'route' => 'blog/author/view',   'prefix' => 'author/'],
    ];

    public function __construct(
        private readonly State $appState,
        private readonly ResourceConnection $resource,
        private readonly StoreManagerInterface $storeManager
    ) {
        parent::__construct();
    }

    protected function configure(): void
    {
        $this->setName('panth:blog:url-rewrite:rebuild');
        $this->setDescription('Rebuild URL rewrites for all blog posts/categories/tags/authors.');
    }

    protected function execute(InputInterface $input, OutputInterface $output): int
    {
        try {
            $this->appState->setAreaCode('adminhtml');
        } catch (\Throwable) {
        }

        try {
            $conn = $this->resource->getConnection();
            $rewriteTable = $this->resource->getTableName('url_rewrite');
            if (!$conn->isTableExists($rewriteTable)) {
                $output->writeln('<error>url_rewrite table missing</error>');
                return 1;
            }

            $stores = $this->storeManager->getStores();
            $total = 0;

            foreach (self::ENTITY_TYPES as $entityType => $meta) {
                $sourceTable = $this->resource->getTableName($meta['table']);
                if (!$conn->isTableExists($sourceTable)) {
                    continue;
                }

                $rows = $conn->fetchAll(
                    $conn->select()->from($sourceTable, [$meta['id'], $meta['urlKey']])
                );

                foreach ($stores as $store) {
                    $storeId = (int) $store->getId();
                    $front = trim((string) $store->getConfig('panth_blog/general/route_frontname'), '/');
                    if ($front === '') {
                        $front = 'blog';
                    }

                    $conn->delete($rewriteTable, [
                        'entity_type = ?' => $entityType,
                        'store_id = ?'    => $storeId,
                    ]);

                    foreach ($rows as $row) {
                        $urlKey = (string) ($row[$meta['urlKey']] ?? '');
                        $entityId = (int) ($row[$meta['id']] ?? 0);
                        if ($urlKey === '' || $entityId === 0) {
                            continue;
                        }

                        $requestPath = $front . '/' . $meta['prefix'] . $urlKey;
                        $targetPath = $meta['route'] . '/slug/' . $urlKey;

                        try {
                            $conn->insert($rewriteTable, [
                                'entity_type'     => $entityType,
                                'entity_id'       => $entityId,
                                'request_path'    => $requestPath,
                                'target_path'     => $targetPath,
                                'redirect_type'   => 0,
                                'store_id'        => $storeId,
                                'is_autogenerated'=> 1,
                            ]);
                            $total++;
                        } catch (\Throwable $e) {
                            $output->writeln('<comment>Skip ' . $entityType . ':' . $entityId . ' - ' . $e->getMessage() . '</comment>');
                        }
                    }
                }
            }

            $output->writeln('<info>Rebuilt ' . $total . ' URL rewrites.</info>');
            return 0;
        } catch (\Throwable $e) {
            $output->writeln('<error>' . $e->getMessage() . '</error>');
            return 1;
        }
    }
}
